In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis =0)
mean_a

array([2. , 8.4])

In [4]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [6]:
N = a.shape[0]
N

5

In [7]:
np.divide(a_centered_sp, (N-1))

2.0

In [8]:
np.cov(np.transpose(a))

array([[1. , 2. ],
       [2. , 4.3]])

In [9]:
import pandas as pd

In [10]:
authors = pd.DataFrame({'author_id':[1,2,3],'author_name':['Тургенев', 'Чехов', 'Островский']})

In [11]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [12]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                      'book_title':['Отцы и дети',
                                    'Рудин', 
                                    'Дворянское гнездо', 
                                    'Толстый и тонкий', 
                                    'Дама с собачкой', 
                                    'Гроза', 
                                    'Таланты и поклонники'], 
                      'price':[450, 300, 350, 500, 450, 370, 290]})

In [13]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [14]:
authors_price = pd.merge(authors, books, on = ['author_id'])

In [15]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [16]:
top5 = authors_price.sort_values(by = ['price'], ascending = False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [17]:
authors_stat = pd.DataFrame({'min_price':authors_price.groupby(['author_name']).price.min(),
                             'max_price':authors_price.groupby(['author_name']).price.max(),
                             'mean_price':authors_price.groupby(['author_name']).price.mean()}).reset_index()

In [18]:
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [19]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [20]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [21]:
book_info = pd.pivot_table(authors_price,
                           values='price',
                           index=['author_name'],
                           columns=['cover'], 
                           aggfunc=np.sum, 
                           fill_value=0).reset_index()
book_info

cover author_name  мягкая  твердая
0      Островский     660        0
1        Тургенев     650      450
2           Чехов       0      950

In [22]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')

In [23]:
book_info2

cover author_name  мягкая  твердая
0      Островский     660        0
1        Тургенев     650      450
2           Чехов       0      950

In [27]:
book_info2 == book_info

cover  author_name  мягкая  твердая
0             True    True     True
1             True    True     True
2             True    True     True

In [1]:
!git init
!git add .
!git status

Initialized empty Git repository in /Users/dias/Documents/Studying/Geek brains/DS/lesson1/.git/
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .ipynb_checkpoints/first_task-checkpoint.ipynb
	new file:   first_task.ipynb



In [2]:
!git commit -m "hw 1"

[master (root-commit) 781fc94] hw 1
 2 files changed, 2110 insertions(+)
 create mode 100644 .ipynb_checkpoints/first_task-checkpoint.ipynb
 create mode 100644 first_task.ipynb


In [3]:
!git checkout -b task1

Switched to a new branch 'task1'


In [4]:
!git remote add origin git@github.com:diassio/data_science_geek.git

In [5]:
!git push -u origin task1

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.49 KiB | 3.49 MiB/s, done.
Total 4 (delta 0), reused 0 (delta 0)
To github.com:diassio/data_science_geek.git
 * [new branch]      task1 -> task1
Branch 'task1' set up to track remote branch 'task1' from 'origin'.
